.\" Manpage for Lucre

.TH man 6 "22 Jan 2022" "0.1.1" "lucre man page"
.SH NAME
Lucre \- Graphics Render Engine 
.SH SYNOPSIS 
engine [options]
.SH DESCRIPTION
Engine is short for "graphics rendering engine" or gfxRenderEngine.
It is a multi-platform rendering backend. The application Lucre is 
to demo the features of gfxRenderEngine.
Visit https://github.com/beaumanvienna/vulkan for more information.

.SH AUTHOR
Team Engine. To contact us, open an issues ticket on https://github.com/beaumanvienna/vulkan. Pull requests are welcome!
