#pragma once

// IMAGES
#define I_ENGINE 0
#define I_CIRCLE 1
#define I_WALKWAY 2
#define I_SIGN_R 3
#define I_OFF 4
#define I_BACK 5
#define I_LOGO_PCSX2 6
#define I_LINES_R 7
#define I_SCENE_No_4_R 8
#define I_SCENE_No_3_R 9
#define I_HOME 10
#define I_SCENE_No_2_R 11
#define I_LOGO_DOLPHIN 12
#define I_BLOOD_ISLAND 13
#define I_WALK 14
#define I_FOLDER_R 15
#define I_PS3_CONTROLLER 16
#define I_UP_DIRECTORY_R 17
#define I_HORN 18
#define I_DROP_SHADOW 19
#define I_CHECKEDBOX 20
#define I_WHITE 21
#define I_GEAR 22
#define I_WALKUP 23
#define I_LOGO_PPSSPP 24
#define I_LUCRE 25
#define I_GEAR_R 26
#define I_BARREL_LARGE 27
#define I_MARLEYLOGO 28
#define I_DISK_EMPTY 29
#define I_CONTROLLER 30
#define I_BACK_R 31
#define I_BARREL 32
#define I_TAB_R 33
#define I_DISK_LOAD_R 34
#define I_GRID 35
#define I_LINES 36
#define I_SIGN3_R 37
#define I_SCENE_No_5_R 38
#define I_SCENE_No_1_R 39
#define I_DISK_SAVE 40
#define I_FOLDER 41
#define I_CLOUDS 42
#define I_SQUARE 43
#define I_VOLCANO_SMOKE 44
#define I_SIGN2_R 45
#define I_CONTROLLER_SETUP 46
#define I_HOME_R 47
#define I_DISK_SAVE_R 48
#define I_STAR 49
#define I_GRID_R 50
#define I_LOGO_MEDNAFEN 51
#define I_WALKDOWN 52
#define I_UP_DIRECTORY 53
#define I_BEACH 54
#define I_OFF_R 55
#define I_LOGO_MUPEN 56
#define I_SETTINGS_BG 57
#define I_VOLCANO_SMOKE_N 58
#define I_DISK_LOAD 59
