#pragma once

// IMAGES
#define I_STAR 0
#define I_SQUARE 1
#define I_SCENE_No_4_R 2
#define I_WALKUP 3
#define I_SCENE_No_6_R 4
#define I_OFF_R 5
#define I_SIGN2_R 6
#define I_FOLDER_R 7
#define I_DISK_EMPTY 8
#define I_BARREL_LARGE 9
#define I_CHECKEDBOX 10
#define I_SCENE_No_9_R 11
#define I_OFF 12
#define I_SETTINGS_BG 13
#define I_PS3_CONTROLLER 14
#define I_LUCRE 15
#define I_DISK_SAVE_R 16
#define I_DROP_SHADOW 17
#define I_DISK_LOAD_R 18
#define I_HOME_R 19
#define I_WALKWAY 20
#define I_SIGN3_R 21
#define I_TAB_R 22
#define I_LINES_R 23
#define I_CIRCLE 24
#define I_GEAR_R 25
#define I_CLOUDS 26
#define I_SIGN_R 27
#define I_SCENE_No_2_R 28
#define I_GRID 29
#define I_VOLCANO_SMOKE 30
#define I_UP_DIRECTORY 31
#define I_CONTROLLER 32
#define I_LOGO_MEDNAFEN 33
#define I_BACK_R 34
#define I_HORN 35
#define I_FOLDER 36
#define I_LINES 37
#define I_WALK 38
#define I_DISK_SAVE 39
#define I_WALKDOWN 40
#define I_BACK 41
#define I_GRID_R 42
#define I_DISK_LOAD 43
#define I_SCENE_No_1_R 44
#define I_UP_DIRECTORY_R 45
#define I_LOGO_PCSX2 46
#define I_HOME 47
#define I_LOGO_PPSSPP 48
#define I_ENGINE 49
#define I_WHITE 50
#define I_SCENE_No_3_R 51
#define I_BEACH 52
#define I_SCENE_No_8_R 53
#define I_LOGO_DOLPHIN 54
#define I_BLOOD_ISLAND 55
#define I_SCENE_No_5_R 56
#define I_BARREL 57
#define I_MARLEYLOGO 58
#define I_GEAR 59
#define I_CONTROLLER_SETUP 60
#define I_SCENE_No_7_R 61
#define I_LOGO_MUPEN 62
#define I_VOLCANO_SMOKE_N 63
